export const ROLE_PERMISSIONS: Record<string, string[]> = {
  Admin:    ['*'],
  HR:       ['timesheet', 'payslips', 'hr-apps', 'teams', 'compliance', 'liaison', 'asp', 'pcf'],
  Employee: ['timesheet', 'payslips', 'hr-apps'],
};

export const LEAD_STATUSES = [
  { id: '1',  name: 'New',                 color: 'bg-blue-600' },
  { id: '2',  name: 'Contacted',           color: 'bg-sky-500' },
  { id: '3',  name: 'Qualified',           color: 'bg-emerald-500' },
  { id: '4',  name: 'Proposal',            color: 'bg-amber-500' },
  { id: '5',  name: 'Negotiation',         color: 'bg-orange-500' },
  { id: '6',  name: 'Closed Won',          color: 'bg-green-600' },
  { id: '7',  name: 'Pending Onboarding',  color: 'bg-violet-500' },
  { id: '8',  name: 'Contract Signing',    color: 'bg-indigo-500' },
  { id: '9',  name: 'Waiting for Payment', color: 'bg-yellow-500' },
  { id: '10', name: 'Turnover',            color: 'bg-teal-600' },
  { id: '11', name: 'Lost',                color: 'bg-red-500' },
];

export const MOCK_AGENTS = [
  { id: 'agent-1', name: 'Maria Santos', type: 'INTERNAL', email: 'maria.santos@agila.ph', contact: '09171234567', role: 'Senior Agent' },
  { id: 'agent-2', name: 'Juan Dela Cruz', type: 'INTERNAL', email: 'juan.delacruz@agila.ph', contact: '09189876543', role: 'Agent' },
  { id: 'agent-3', name: 'Ana Reyes', type: 'EXTERNAL', email: 'ana.reyes@agila.ph', contact: '09201112233', role: 'Agent' },
  { id: 'agent-4', name: 'Carlos Garcia', type: 'INTERNAL', email: 'carlos.garcia@agila.ph', contact: '09334455667', role: 'Junior Agent' },
];

export const BUSINESS_TYPES = [
  'Sole Proprietorship',
  'Partnership',
  'Corporation',
  'One Person Corporation (OPC)',
];

export const LEAD_SOURCES = [
  'Manual',
  'Facebook AI',
  'Referral',
  'Walk-in',
  'Website',
  'Email Campaign',
  'Cold Call',
  'Social Media',
  'Other',
];

import type { Lead } from './types';

export const INITIAL_LEADS: Lead[] = [
  {
    id: 'lead-1',
    firstName: 'Roberto',
    lastName: 'Villanueva',
    contactNumber: '09171234567',
    email: 'roberto.v@email.com',
    businessType: 'Sole Proprietorship',
    leadSource: 'Walk-in',
    statusId: '1',
    assignedAgentId: 'agent-1',
    notes: 'Interested in business registration services',
    createdAt: '2026-03-08T09:00:00Z',
    updatedAt: '2026-03-08T09:00:00Z',
  },
  {
    id: 'lead-2',
    firstName: 'Patricia',
    lastName: 'Lim',
    contactNumber: '09189876543',
    email: 'patricia.lim@gmail.com',
    businessType: 'Corporation',
    leadSource: 'Referral',
    statusId: '1',
    assignedAgentId: 'agent-2',
    notes: 'Referred by existing client',
    createdAt: '2026-03-07T14:30:00Z',
    updatedAt: '2026-03-07T14:30:00Z',
  },
  {
    id: 'lead-3',
    firstName: 'Marco',
    lastName: 'Tan',
    contactNumber: '09201112233',
    email: 'marco.tan@business.com',
    businessType: 'Partnership',
    leadSource: 'Website',
    statusId: '2',
    assignedAgentId: 'agent-1',
    notes: 'Inquired about tax compliance packages',
    createdAt: '2026-03-05T11:00:00Z',
    updatedAt: '2026-03-06T10:00:00Z',
  },
  {
    id: 'lead-4',
    firstName: 'Isabella',
    lastName: 'Cruz',
    contactNumber: '09334455667',
    email: 'isabella.cruz@corp.ph',
    businessType: 'Corporation',
    leadSource: 'Facebook AI',
    statusId: '3',
    assignedAgentId: 'agent-3',
    notes: 'High-value prospect, multiple branches',
    createdAt: '2026-03-01T08:00:00Z',
    updatedAt: '2026-03-04T16:00:00Z',
  },
  {
    id: 'lead-5',
    firstName: 'Diego',
    lastName: 'Aquino',
    contactNumber: '09157788990',
    email: 'diego.aquino@startup.ph',
    businessType: 'One Person Corporation (OPC)',
    leadSource: 'Cold Call',
    statusId: '4',
    assignedAgentId: 'agent-2',
    notes: 'Reviewing proposal for annual tax services',
    createdAt: '2026-02-25T10:00:00Z',
    updatedAt: '2026-03-03T14:00:00Z',
  },
  {
    id: 'lead-6',
    firstName: 'Carmen',
    lastName: 'Reyes',
    contactNumber: '09268899001',
    email: 'carmen.reyes@firm.com',
    businessType: 'Partnership',
    leadSource: 'Email Campaign',
    statusId: '5',
    assignedAgentId: 'agent-4',
    notes: 'Negotiating package pricing',
    createdAt: '2026-02-20T09:00:00Z',
    updatedAt: '2026-03-02T11:00:00Z',
  },
  {
    id: 'lead-7',
    firstName: 'Angelo',
    lastName: 'Mendoza',
    contactNumber: '09112233445',
    email: 'angelo.m@company.ph',
    businessType: 'Corporation',
    leadSource: 'Referral',
    statusId: '6',
    assignedAgentId: 'agent-1',
    notes: 'Signed up for full compliance package',
    createdAt: '2026-02-15T08:00:00Z',
    updatedAt: '2026-02-28T15:00:00Z',
  },
  {
    id: 'lead-8',
    firstName: 'Sofia',
    lastName: 'Bautista',
    contactNumber: '09445566778',
    email: 'sofia.b@email.com',
    businessType: 'Sole Proprietorship',
    leadSource: 'Social Media',
    statusId: '2',
    assignedAgentId: 'agent-3',
    notes: 'Following up on initial inquiry',
    createdAt: '2026-03-06T13:00:00Z',
    updatedAt: '2026-03-07T09:00:00Z',
  },
  {
    id: 'lead-9',
    firstName: 'Enrique',
    lastName: 'Pascual',
    contactNumber: '09567788990',
    email: '',
    businessType: 'Sole Proprietorship',
    leadSource: 'Walk-in',
    statusId: '11',
    assignedAgentId: 'agent-4',
    notes: 'Chose different provider',
    createdAt: '2026-02-10T10:00:00Z',
    updatedAt: '2026-02-18T12:00:00Z',
  },
  {
    id: 'lead-10',
    firstName: 'Lucia',
    lastName: 'Dimaculangan',
    contactNumber: '09171001234',
    email: 'lucia.d@enterprise.ph',
    businessType: 'Corporation',
    leadSource: 'Website',
    statusId: '7',
    assignedAgentId: 'agent-1',
    notes: 'Onboarding documents sent, awaiting signed forms',
    createdAt: '2026-02-28T09:00:00Z',
    updatedAt: '2026-03-05T14:00:00Z',
  },
  {
    id: 'lead-11',
    firstName: 'Rafael',
    lastName: 'Soriano',
    contactNumber: '09189002345',
    email: 'rafael.soriano@biz.ph',
    businessType: 'Partnership',
    leadSource: 'Referral',
    statusId: '8',
    assignedAgentId: 'agent-2',
    notes: 'Contract sent for e-signature',
    createdAt: '2026-02-20T11:00:00Z',
    updatedAt: '2026-03-04T10:00:00Z',
  },
  {
    id: 'lead-12',
    firstName: 'Teresa',
    lastName: 'Navarro',
    contactNumber: '09203004567',
    email: 'teresa.navarro@firm.com',
    businessType: 'One Person Corporation (OPC)',
    leadSource: 'Email Campaign',
    statusId: '9',
    assignedAgentId: 'agent-3',
    notes: 'Contract signed, invoice issued — awaiting payment',
    createdAt: '2026-02-15T08:00:00Z',
    updatedAt: '2026-03-03T16:00:00Z',
    accountCreated: true,
    isPaid: false,
    clientNo: '2026-1001',
  },
  {
    id: 'lead-13',
    firstName: 'Gabriel',
    lastName: 'Hernandez',
    contactNumber: '09334005678',
    email: 'gabriel.h@startup.ph',
    businessType: 'Sole Proprietorship',
    leadSource: 'Walk-in',
    statusId: '10',
    assignedAgentId: 'agent-1',
    notes: 'Payment confirmed — generating Job Order, Invoice & TOS',
    createdAt: '2026-02-10T10:00:00Z',
    updatedAt: '2026-03-02T09:00:00Z',
    accountCreated: true,
    isPaid: true,
    clientNo: '2026-1002',
  },
];
