import type { Client } from './types';

export const INITIAL_CLIENTS: Client[] = [
  {
    id: 'client-1',
    clientNo: '2026-0001',
    businessName: 'Villanueva Trading Co.',
    companyCode: 'VTC-001',
    authorizedRep: 'Roberto Villanueva',
    email: 'roberto.v@villanuevatrading.ph',
    phone: '09171234567',
    status: 'Active',
    agentId: 'agent-1',
    planDetails: {
      basePlan: 'essentials-non-vat',
      displayName: 'Essentials (Non-VAT)',
      customFeaturesIncluded: [
        'DTI / SEC Registration',
        "Mayor's Permit Processing",
        'BIR Business Registration',
        'BIR Compliance Filing Services',
        "Annual Mayor's Permit Renewal",
        'Annual Income Tax Return',
      ],
      customFeaturesMore: [],
      customFreebies: ['Free Tax Calendar & Reminders', 'Free Compliance Checklist'],
      customPrice: '2,500',
      selectedServiceIds: [],
    },
    clientServices: [
      { id: 'cs-1', serviceId: 'svc-01', serviceName: 'BIR Registration (New Business)', rate: 5000 },
    ],
    isPaid: true,
    commissionPaid: false,
    finalAmount: 2500,
    hasUpsell: false,
    upsellAmount: 0,
    createdAt: '2025-10-15T09:00:00Z',
  },
  {
    id: 'client-2',
    clientNo: '2026-0002',
    businessName: 'Lim Holdings Corporation',
    companyCode: 'LHC-002',
    authorizedRep: 'Patricia Lim',
    email: 'patricia.lim@limholdings.ph',
    phone: '09189876543',
    status: 'Active',
    agentId: 'agent-2',
    planDetails: {
      basePlan: 'agila360-vat',
      displayName: 'Agila360 (VAT)',
      customFeaturesIncluded: [
        'DTI / SEC Registration',
        "Mayor's Permit Processing",
        'BIR Business Registration',
        'BIR Compliance Filing Services',
        "Annual Mayor's Permit Renewal",
        'Annual Income Tax Return',
      ],
      customFeaturesMore: [
        'SSS Registration / Remittances',
        'PhilHealth Registration / Remittances',
        'PAGIBIG Registration / Remittances',
        'DOLE Registration',
        'Payroll Services',
        'Monthly On-Site Check Up',
      ],
      customFreebies: ['Free Tax Calendar & Reminders', 'Free Compliance Checklist', 'Free Business Registration Guide', 'Free Tax Consultation (1st Session)'],
      customPrice: '6,500',
      selectedServiceIds: [],
    },
    clientServices: [
      { id: 'cs-2', serviceId: 'svc-13', serviceName: 'Annual ITR Filing (1702)', rate: 10000 },
      { id: 'cs-3', serviceId: 'svc-22', serviceName: 'SEC Registration (New Corporation)', rate: 15000 },
    ],
    isPaid: true,
    commissionPaid: false,
    finalAmount: 6500,
    hasUpsell: true,
    upsellAmount: 5000,
    createdAt: '2025-08-22T14:30:00Z',
  },
  {
    id: 'client-3',
    clientNo: '2026-0003',
    businessName: 'Tan & Associates Law Firm',
    companyCode: 'TAL-003',
    authorizedRep: 'Marco Tan',
    email: 'marco.tan@tanlaw.ph',
    phone: '09201112233',
    status: 'Active',
    agentId: 'agent-1',
    planDetails: {
      basePlan: 'essentials-vat',
      displayName: 'Essentials (VAT)',
      customFeaturesIncluded: [
        'DTI / SEC Registration',
        "Mayor's Permit Processing",
        'BIR Business Registration',
        'BIR Compliance Filing Services',
        "Annual Mayor's Permit Renewal",
        'Annual Income Tax Return',
      ],
      customFeaturesMore: [],
      customFreebies: ['Free Tax Calendar & Reminders', 'Free Compliance Checklist'],
      customPrice: '4,500',
      selectedServiceIds: [],
    },
    clientServices: [],
    isPaid: true,
    commissionPaid: false,
    finalAmount: 4500,
    hasUpsell: false,
    upsellAmount: 0,
    createdAt: '2025-11-05T11:00:00Z',
  },
  {
    id: 'client-4',
    clientNo: '2026-0004',
    businessName: 'Cruz Enterprises Inc.',
    companyCode: 'CEI-004',
    authorizedRep: 'Isabella Cruz',
    email: 'isabella.cruz@cruzenterprises.ph',
    phone: '09334455667',
    status: 'Pending',
    agentId: 'agent-3',
    planDetails: {
      basePlan: 'agila360-non-vat',
      displayName: 'Agila360 (Non-VAT)',
      customFeaturesIncluded: [
        'DTI / SEC Registration',
        "Mayor's Permit Processing",
        'BIR Business Registration',
        'BIR Compliance Filing Services',
        "Annual Mayor's Permit Renewal",
        'Annual Income Tax Return',
      ],
      customFeaturesMore: [
        'SSS Registration / Remittances',
        'PhilHealth Registration / Remittances',
        'PAGIBIG Registration / Remittances',
        'DOLE Registration',
        'Payroll Services',
        'Monthly On-Site Check Up',
      ],
      customFreebies: ['Free Tax Calendar & Reminders', 'Free Compliance Checklist', 'Free Business Registration Guide', 'Free Tax Consultation (1st Session)'],
      customPrice: '5,000',
      selectedServiceIds: [],
    },
    clientServices: [
      { id: 'cs-4', serviceId: 'svc-04', serviceName: 'TIN Application', rate: 2000 },
    ],
    isPaid: false,
    commissionPaid: false,
    finalAmount: 5000,
    hasUpsell: false,
    upsellAmount: 0,
    createdAt: '2026-01-10T08:00:00Z',
  },
  {
    id: 'client-5',
    clientNo: '2026-0005',
    businessName: 'Aquino Tech Solutions',
    companyCode: 'ATS-005',
    authorizedRep: 'Diego Aquino',
    email: 'diego.aquino@aquinotech.ph',
    phone: '09157788990',
    status: 'Active',
    agentId: 'agent-2',
    planDetails: {
      basePlan: 'vip',
      displayName: 'VIP',
      customFeaturesIncluded: [
        'Everything in Agila360',
        'Unlimited Users',
        'Dedicated Account Manager',
        '24/7 Priority Support',
        'Custom Features & Integrations',
        'White-label Options',
      ],
      customFeaturesMore: [
        'Multi-branch Management',
        'Weekly On-Site Consultation',
        'Dedicated Development Team',
        'Custom Reporting Dashboard',
        'API Access for Integrations',
        'Advanced Security Features',
      ],
      customFreebies: ['Free Tax Calendar & Reminders', 'Free Compliance Checklist', 'Free Custom System Development', 'Free Annual Strategic Planning'],
      customPrice: '15,000',
      selectedServiceIds: [],
    },
    clientServices: [
      { id: 'cs-5', serviceId: 'svc-19', serviceName: 'Annual Alpha List Preparation', rate: 5000 },
      { id: 'cs-6', serviceId: 'svc-10', serviceName: 'Quarterly VAT Filing (2550Q)', rate: 4000 },
    ],
    isPaid: true,
    commissionPaid: false,
    finalAmount: 15000,
    hasUpsell: true,
    upsellAmount: 8000,
    createdAt: '2025-06-01T10:00:00Z',
  },
  {
    id: 'client-6',
    clientNo: '2026-0006',
    businessName: 'Reyes Law Office',
    companyCode: 'RLO-006',
    authorizedRep: 'Carmen Reyes',
    email: 'carmen.reyes@reyeslaw.ph',
    phone: '09268899001',
    status: 'Active',
    agentId: 'agent-4',
    planDetails: {
      basePlan: 'starter',
      displayName: 'Starter',
      customFeaturesIncluded: [
        'DTI Registration',
        "Mayor's Permit Processing",
        'BIR Business Registration',
        'BIR Compliance Filing Services',
        "Annual Mayor's Permit Renewal",
        'Annual Income Tax Return',
      ],
      customFeaturesMore: [],
      customFreebies: ['Free Tax Calendar & Reminders', 'Free Compliance Checklist'],
      customPrice: '1,500',
      selectedServiceIds: [],
    },
    clientServices: [],
    isPaid: true,
    commissionPaid: false,
    finalAmount: 1500,
    hasUpsell: false,
    upsellAmount: 0,
    createdAt: '2025-12-20T09:00:00Z',
  },
  {
    id: 'client-7',
    clientNo: '2026-0007',
    businessName: 'Santos Food Corporation',
    companyCode: 'SFC-007',
    authorizedRep: 'Angelo Santos',
    email: 'angelo.santos@santosfood.ph',
    phone: '09112233445',
    status: 'Pending',
    agentId: 'agent-1',
    planDetails: {
      basePlan: 'essentials-non-vat',
      displayName: 'Essentials (Non-VAT)',
      customFeaturesIncluded: [
        'DTI / SEC Registration',
        "Mayor's Permit Processing",
        'BIR Business Registration',
        'BIR Compliance Filing Services',
        "Annual Mayor's Permit Renewal",
        'Annual Income Tax Return',
      ],
      customFeaturesMore: [],
      customFreebies: ['Free Tax Calendar & Reminders'],
      customPrice: '2,500',
      selectedServiceIds: [],
    },
    clientServices: [
      { id: 'cs-7', serviceId: 'svc-05', serviceName: 'Books of Account Registration', rate: 2500 },
    ],
    isPaid: false,
    commissionPaid: false,
    finalAmount: 2500,
    hasUpsell: false,
    upsellAmount: 0,
    createdAt: '2026-02-01T10:00:00Z',
  },
  {
    id: 'client-8',
    clientNo: '2026-0008',
    businessName: 'Bautista Retail Shop',
    companyCode: 'BRS-008',
    authorizedRep: 'Sofia Bautista',
    email: 'sofia.b@bautistaretail.ph',
    phone: '09445566778',
    status: 'Active',
    agentId: 'agent-3',
    planDetails: {
      basePlan: 'starter',
      displayName: 'Starter',
      customFeaturesIncluded: [
        'DTI Registration',
        "Mayor's Permit Processing",
        'BIR Business Registration',
        'BIR Compliance Filing Services',
        "Annual Mayor's Permit Renewal",
        'Annual Income Tax Return',
      ],
      customFeaturesMore: [],
      customFreebies: ['Free Tax Calendar & Reminders', 'Free Compliance Checklist'],
      customPrice: '1,500',
      selectedServiceIds: [],
    },
    clientServices: [],
    isPaid: true,
    commissionPaid: false,
    finalAmount: 1500,
    hasUpsell: false,
    upsellAmount: 0,
    createdAt: '2025-09-15T13:00:00Z',
  },
  {
    id: 'client-9',
    clientNo: '2026-0009',
    businessName: 'Pascual Manufacturing Inc.',
    companyCode: 'PMI-009',
    authorizedRep: 'Enrique Pascual',
    email: 'enrique.p@pascualmfg.ph',
    phone: '09567788990',
    status: 'Active',
    agentId: 'agent-2',
    planDetails: {
      basePlan: 'agila360-vat',
      displayName: 'Agila360 (VAT)',
      customFeaturesIncluded: [
        'DTI / SEC Registration',
        "Mayor's Permit Processing",
        'BIR Business Registration',
        'BIR Compliance Filing Services',
        "Annual Mayor's Permit Renewal",
        'Annual Income Tax Return',
      ],
      customFeaturesMore: [
        'SSS Registration / Remittances',
        'PhilHealth Registration / Remittances',
        'PAGIBIG Registration / Remittances',
        'DOLE Registration',
        'Payroll Services',
        'Monthly On-Site Check Up',
      ],
      customFreebies: ['Free Tax Calendar & Reminders', 'Free Compliance Checklist', 'Free Business Registration Guide', 'Free Tax Consultation (1st Session)'],
      customPrice: '6,500',
      selectedServiceIds: [],
    },
    clientServices: [
      { id: 'cs-8', serviceId: 'svc-16', serviceName: 'Monthly Withholding Tax (0619E)', rate: 3000 },
      { id: 'cs-9', serviceId: 'svc-17', serviceName: 'Annual Withholding Tax (1604E)', rate: 5000 },
    ],
    isPaid: true,
    commissionPaid: false,
    finalAmount: 6500,
    hasUpsell: false,
    upsellAmount: 0,
    createdAt: '2025-07-10T08:00:00Z',
  },
  {
    id: 'client-10',
    clientNo: '2026-0010',
    businessName: 'Dimaculangan Import/Export',
    companyCode: 'DIE-010',
    authorizedRep: 'Lucia Dimaculangan',
    email: 'lucia.d@dimaculangan.ph',
    phone: '09171001234',
    status: 'Pending',
    agentId: 'agent-4',
    planDetails: null,
    clientServices: [],
    isPaid: false,
    commissionPaid: false,
    finalAmount: 0,
    hasUpsell: false,
    upsellAmount: 0,
    createdAt: '2026-03-01T11:00:00Z',
  },
  {
    id: 'client-11',
    clientNo: '2026-0011',
    businessName: 'Garcia Construction Corp.',
    companyCode: 'GCC-011',
    authorizedRep: 'Carlos Garcia Jr.',
    email: 'carlos.jr@garciaconstruction.ph',
    phone: '09189002345',
    status: 'Active',
    agentId: 'agent-1',
    planDetails: {
      basePlan: 'essentials-vat',
      displayName: 'Essentials (VAT)',
      customFeaturesIncluded: [
        'DTI / SEC Registration',
        "Mayor's Permit Processing",
        'BIR Business Registration',
        'BIR Compliance Filing Services',
        "Annual Mayor's Permit Renewal",
        'Annual Income Tax Return',
      ],
      customFeaturesMore: [],
      customFreebies: ['Free Tax Calendar & Reminders', 'Free Compliance Checklist'],
      customPrice: '4,500',
      selectedServiceIds: [],
    },
    clientServices: [
      { id: 'cs-10', serviceId: 'svc-12', serviceName: 'Annual ITR Filing (1701)', rate: 8000 },
    ],
    isPaid: true,
    commissionPaid: false,
    finalAmount: 4500,
    hasUpsell: true,
    upsellAmount: 3000,
    createdAt: '2025-05-18T08:00:00Z',
  },
  {
    id: 'client-12',
    clientNo: '2026-0012',
    businessName: 'Mendoza Digital Agency',
    companyCode: 'MDA-012',
    authorizedRep: 'Rafael Mendoza',
    email: 'rafael.m@mendozadigital.ph',
    phone: '09203004567',
    status: 'Active',
    agentId: 'agent-3',
    planDetails: {
      basePlan: 'starter',
      displayName: 'Starter',
      customFeaturesIncluded: [
        'DTI Registration',
        "Mayor's Permit Processing",
        'BIR Business Registration',
        'BIR Compliance Filing Services',
        "Annual Mayor's Permit Renewal",
        'Annual Income Tax Return',
      ],
      customFeaturesMore: [],
      customFreebies: ['Free Tax Calendar & Reminders'],
      customPrice: '1,500',
      selectedServiceIds: [],
    },
    clientServices: [
      { id: 'cs-11', serviceId: 'svc-03', serviceName: 'Annual Registration Fee (0605)', rate: 1500 },
    ],
    isPaid: true,
    commissionPaid: false,
    finalAmount: 1500,
    hasUpsell: false,
    upsellAmount: 0,
    createdAt: '2025-11-25T09:00:00Z',
  },
];
