import type {
  AOTeamMember,
  AOTask,
  AONotification,
  AODiscussionMessage,
} from './types';

// ── Current Account Officer ───────────────────────────────
export const CURRENT_AO: AOTeamMember = {
  id: 'ao-1',
  name: 'Camille Reyes',
  email: 'camille.reyes@agila.ph',
  avatar: 'CR',
  department: 'Account Management',
};

// ── Team Members (assignees) ──────────────────────────────
export const AO_TEAM_MEMBERS: AOTeamMember[] = [
  CURRENT_AO,
  { id: 'ao-2', name: 'Daniel Magsaysay', email: 'daniel.m@agila.ph', avatar: 'DM', department: 'Compliance 1' },
  { id: 'ao-3', name: 'Bianca Torres', email: 'bianca.t@agila.ph', avatar: 'BT', department: 'Liaison 2' },
  { id: 'ao-4', name: 'Rafael Aquino', email: 'rafael.a@agila.ph', avatar: 'RA', department: 'Liaison 1' },
  { id: 'ao-5', name: 'Sofia Cruz', email: 'sofia.c@agila.ph', avatar: 'SC', department: 'Compliance 2' },
];

// ── Tasks ─────────────────────────────────────────────────
export const INITIAL_AO_TASKS: AOTask[] = [
  {
    id: 'task-1',
    title: 'BIR 2551Q Filing',
    description: 'File quarterly percentage tax return for Q1 2026. Ensure all sales invoices are reconciled before submission.',
    status: 'In Progress',
    priority: 'High',
    clientId: 'client-1',
    assigneeId: 'ao-3',
    dueDate: '2026-03-15',
    createdAt: '2026-03-01T08:00:00Z',
    updatedAt: '2026-03-10T14:30:00Z',
    comments: [
      { id: 'c-1', authorId: 'ao-3', authorName: 'Bianca Torres', content: 'Sales invoices reconciled. Ready for filing.', createdAt: '2026-03-08T10:00:00Z' },
      { id: 'c-2', authorId: 'ao-1', authorName: 'Camille Reyes', content: 'Good. Please file before the 15th deadline.', createdAt: '2026-03-08T11:30:00Z' },
    ],
    tags: ['BIR', 'Tax Filing', 'Quarterly'],
  },
  {
    id: 'task-2',
    title: "Mayor's Permit Renewal",
    description: "Process annual Mayor's Permit renewal. Gather all barangay clearances and updated DTI certificate.",
    status: 'To Do',
    priority: 'Urgent',
    clientId: 'client-2',
    assigneeId: 'ao-4',
    dueDate: '2026-03-20',
    createdAt: '2026-03-02T09:00:00Z',
    updatedAt: '2026-03-02T09:00:00Z',
    comments: [],
    tags: ['LGU', 'Permit', 'Annual'],
  },
  {
    id: 'task-3',
    title: 'SSS Monthly Remittance',
    description: 'Process SSS contribution remittance for February 2026. Verify employee count and contribution amounts.',
    status: 'Done',
    priority: 'Medium',
    clientId: 'client-3',
    assigneeId: 'ao-5',
    dueDate: '2026-03-10',
    createdAt: '2026-02-25T08:00:00Z',
    updatedAt: '2026-03-09T16:00:00Z',
    comments: [
      { id: 'c-3', authorId: 'ao-5', authorName: 'Sofia Cruz', content: 'Remittance processed and confirmed. SBR No. 2026-SSS-0892.', createdAt: '2026-03-09T16:00:00Z' },
    ],
    tags: ['SSS', 'Remittance', 'Monthly'],
  },
  {
    id: 'task-4',
    title: 'SEC Annual Report Submission',
    description: 'Prepare and file the Annual Financial Statements and General Information Sheet (GIS) to SEC.',
    status: 'Review',
    priority: 'High',
    clientId: 'client-2',
    assigneeId: 'ao-2',
    dueDate: '2026-04-15',
    createdAt: '2026-03-05T10:00:00Z',
    updatedAt: '2026-03-11T09:00:00Z',
    comments: [
      { id: 'c-4', authorId: 'ao-2', authorName: 'Daniel Magsaysay', content: 'GIS drafted. Awaiting client signature on verified pages.', createdAt: '2026-03-10T14:00:00Z' },
      { id: 'c-5', authorId: 'ao-1', authorName: 'Camille Reyes', content: 'Sent email to Patricia for signature. Follow up by Friday.', createdAt: '2026-03-11T09:00:00Z' },
    ],
    tags: ['SEC', 'Annual Report', 'Compliance'],
  },
  {
    id: 'task-5',
    title: 'PhilHealth RF-1 Monthly',
    description: 'Submit PhilHealth monthly remittance report for all enrolled employees.',
    status: 'In Progress',
    priority: 'Medium',
    clientId: 'client-4',
    assigneeId: 'ao-5',
    dueDate: '2026-03-14',
    createdAt: '2026-03-01T08:30:00Z',
    updatedAt: '2026-03-10T10:00:00Z',
    comments: [
      { id: 'c-6', authorId: 'ao-5', authorName: 'Sofia Cruz', content: 'Computing contributions for 12 employees.', createdAt: '2026-03-10T10:00:00Z' },
    ],
    tags: ['PhilHealth', 'Remittance', 'Monthly'],
  },
  {
    id: 'task-6',
    title: 'BIR 2307 Preparation',
    description: 'Prepare Certificate of Creditable Tax Withheld at Source (BIR Form 2307) for all suppliers.',
    status: 'To Do',
    priority: 'Low',
    clientId: 'client-5',
    assigneeId: 'ao-3',
    dueDate: '2026-03-31',
    createdAt: '2026-03-06T11:00:00Z',
    updatedAt: '2026-03-06T11:00:00Z',
    comments: [],
    tags: ['BIR', 'Withholding Tax'],
  },
  {
    id: 'task-7',
    title: 'Pag-IBIG HDMF Remittance',
    description: 'Process Pag-IBIG monthly contribution remittance. Include newly hired employees from Feb.',
    status: 'To Do',
    priority: 'Medium',
    clientId: 'client-6',
    assigneeId: 'ao-5',
    dueDate: '2026-03-18',
    createdAt: '2026-03-03T09:00:00Z',
    updatedAt: '2026-03-03T09:00:00Z',
    comments: [],
    tags: ['Pag-IBIG', 'Remittance', 'Monthly'],
  },
  {
    id: 'task-8',
    title: 'Payroll Processing - March',
    description: 'Compute and process monthly payroll including overtime, deductions, and net pay for all employees.',
    status: 'In Progress',
    priority: 'High',
    clientId: 'client-7',
    assigneeId: 'ao-1',
    dueDate: '2026-03-25',
    createdAt: '2026-03-10T08:00:00Z',
    updatedAt: '2026-03-11T10:00:00Z',
    comments: [
      { id: 'c-7', authorId: 'ao-1', authorName: 'Camille Reyes', content: 'Gathering attendance and overtime logs from HR.', createdAt: '2026-03-11T10:00:00Z' },
    ],
    tags: ['Payroll', 'Monthly'],
  },
  {
    id: 'task-9',
    title: 'DTI Business Name Registration',
    description: 'Register new business name with DTI. Client expanding to new trade name for e-commerce branch.',
    status: 'Done',
    priority: 'Medium',
    clientId: 'client-8',
    assigneeId: 'ao-4',
    dueDate: '2026-03-08',
    createdAt: '2026-02-20T09:00:00Z',
    updatedAt: '2026-03-07T15:00:00Z',
    comments: [
      { id: 'c-8', authorId: 'ao-4', authorName: 'Rafael Aquino', content: 'DTI certificate issued. Registration No. DTI-2026-0428.', createdAt: '2026-03-07T15:00:00Z' },
    ],
    tags: ['DTI', 'Registration'],
  },
  {
    id: 'task-10',
    title: 'BIR 1601-C Monthly Withholding',
    description: 'File Monthly Remittance Return of Income Taxes Withheld on Compensation.',
    status: 'Review',
    priority: 'High',
    clientId: 'client-1',
    assigneeId: 'ao-3',
    dueDate: '2026-03-12',
    createdAt: '2026-03-01T09:00:00Z',
    updatedAt: '2026-03-11T08:30:00Z',
    comments: [
      { id: 'c-9', authorId: 'ao-3', authorName: 'Bianca Torres', content: 'Return prepared. Waiting for AO review before eFPS submission.', createdAt: '2026-03-11T08:30:00Z' },
    ],
    tags: ['BIR', 'Withholding Tax', 'Monthly'],
  },
  {
    id: 'task-11',
    title: 'DOLE Compliance Audit Prep',
    description: 'Prepare labor compliance documents for upcoming DOLE inspection. Review employment contracts and OSHS records.',
    status: 'To Do',
    priority: 'Urgent',
    clientId: 'client-9',
    assigneeId: 'ao-2',
    dueDate: '2026-03-22',
    createdAt: '2026-03-09T10:00:00Z',
    updatedAt: '2026-03-09T10:00:00Z',
    comments: [],
    tags: ['DOLE', 'Compliance', 'Audit'],
  },
  {
    id: 'task-12',
    title: 'Monthly On-Site Check Up',
    description: 'Conduct monthly on-site visit. Review books, check compliance status, and address client concerns.',
    status: 'To Do',
    priority: 'Low',
    clientId: 'client-10',
    assigneeId: 'ao-1',
    dueDate: '2026-03-28',
    createdAt: '2026-03-08T08:00:00Z',
    updatedAt: '2026-03-08T08:00:00Z',
    comments: [],
    tags: ['On-Site', 'Monthly'],
  },
];

// ── Notifications ─────────────────────────────────────────
export const INITIAL_AO_NOTIFICATIONS: AONotification[] = [
  {
    id: 'notif-1',
    type: 'status_change',
    title: 'Task Status Updated',
    message: 'BIR 2551Q Filing moved to "In Progress" by Bianca Torres',
    taskId: 'task-1',
    clientId: 'client-1',
    isRead: false,
    createdAt: '2026-03-10T14:30:00Z',
  },
  {
    id: 'notif-2',
    type: 'comment',
    title: 'New Comment',
    message: 'Daniel Magsaysay commented on SEC Annual Report Submission',
    taskId: 'task-4',
    clientId: 'client-2',
    isRead: false,
    createdAt: '2026-03-10T14:00:00Z',
  },
  {
    id: 'notif-3',
    type: 'status_change',
    title: 'Task Completed',
    message: 'SSS Monthly Remittance marked as "Done" by Sofia Cruz',
    taskId: 'task-3',
    clientId: 'client-3',
    isRead: true,
    createdAt: '2026-03-09T16:00:00Z',
  },
  {
    id: 'notif-4',
    type: 'assignment',
    title: 'New Task Assigned',
    message: 'You have been assigned "Payroll Processing - March" for Mendoza Enterprises',
    taskId: 'task-8',
    clientId: 'client-7',
    isRead: false,
    createdAt: '2026-03-10T08:00:00Z',
  },
  {
    id: 'notif-5',
    type: 'message',
    title: 'New Message',
    message: 'Patricia Lim sent a message regarding SEC Annual Report',
    clientId: 'client-2',
    isRead: false,
    createdAt: '2026-03-11T07:45:00Z',
  },
  {
    id: 'notif-6',
    type: 'status_change',
    title: 'Task Under Review',
    message: 'BIR 1601-C Monthly Withholding moved to "Review"',
    taskId: 'task-10',
    clientId: 'client-1',
    isRead: true,
    createdAt: '2026-03-11T08:30:00Z',
  },
  {
    id: 'notif-7',
    type: 'comment',
    title: 'New Comment',
    message: 'Sofia Cruz commented on PhilHealth RF-1 Monthly',
    taskId: 'task-5',
    clientId: 'client-4',
    isRead: true,
    createdAt: '2026-03-10T10:00:00Z',
  },
  {
    id: 'notif-8',
    type: 'assignment',
    title: 'Task Reassigned',
    message: 'DOLE Compliance Audit Prep reassigned to Daniel Magsaysay',
    taskId: 'task-11',
    clientId: 'client-9',
    isRead: false,
    createdAt: '2026-03-09T10:00:00Z',
  },
];

// ── Discussion Messages ───────────────────────────────────
export const INITIAL_AO_DISCUSSIONS: AODiscussionMessage[] = [
  // Client 1 - Villanueva Trading
  {
    id: 'msg-1',
    clientId: 'client-1',
    senderId: 'client-1',
    senderName: 'Roberto Villanueva',
    senderRole: 'client',
    content: 'Hi, when is the deadline for the quarterly tax filing?',
    createdAt: '2026-03-07T09:15:00Z',
  },
  {
    id: 'msg-2',
    clientId: 'client-1',
    senderId: 'ao-1',
    senderName: 'Camille Reyes',
    senderRole: 'account-officer',
    content: 'Good morning, Roberto! The BIR 2551Q deadline is March 15. We are already processing it. Will update you once filed.',
    createdAt: '2026-03-07T09:30:00Z',
  },
  {
    id: 'msg-3',
    clientId: 'client-1',
    senderId: 'client-1',
    senderName: 'Roberto Villanueva',
    senderRole: 'client',
    content: 'Great, thank you! Also, please send me the 2307 forms when ready.',
    createdAt: '2026-03-07T09:45:00Z',
  },
  // Client 2 - Lim Holdings
  {
    id: 'msg-4',
    clientId: 'client-2',
    senderId: 'client-2',
    senderName: 'Patricia Lim',
    senderRole: 'client',
    content: "Hi Camille, I received the GIS draft. Will review and sign today.",
    createdAt: '2026-03-11T07:45:00Z',
  },
  {
    id: 'msg-5',
    clientId: 'client-2',
    senderId: 'ao-1',
    senderName: 'Camille Reyes',
    senderRole: 'account-officer',
    content: 'Thank you, Patricia! Please send the signed pages via email or upload here. We need to submit to SEC by April 15.',
    createdAt: '2026-03-11T08:00:00Z',
  },
  // Client 4 - Navarro Construction
  {
    id: 'msg-6',
    clientId: 'client-4',
    senderId: 'client-4',
    senderName: 'Elena Navarro',
    senderRole: 'client',
    content: 'We hired 3 new employees last month. Do we need to update the PhilHealth enrollment?',
    createdAt: '2026-03-09T14:00:00Z',
  },
  {
    id: 'msg-7',
    clientId: 'client-4',
    senderId: 'ao-1',
    senderName: 'Camille Reyes',
    senderRole: 'account-officer',
    content: "Yes, we'll need their PhilHealth numbers and employment details. Please send them over and we'll handle the enrollment.",
    createdAt: '2026-03-09T14:30:00Z',
  },
  {
    id: 'msg-8',
    clientId: 'client-4',
    senderId: 'client-4',
    senderName: 'Elena Navarro',
    senderRole: 'client',
    content: "I'll email the info this afternoon. Thank you!",
    createdAt: '2026-03-09T15:00:00Z',
  },
];
