// ── Mock Liaison Data ─────────────────────────────────────
// Frontend-only mock data for the Liaison portal.

import type { AOTask, AOTeamMember } from './types';

// ── Liaison Team ──────────────────────────────────────────
export const LIAISON_TEAM: AOTeamMember[] = [
  { id: 'lia-1', name: 'Bianca Torres', email: 'bianca.t@agila.ph', avatar: 'BT', department: 'Liaison' },
  { id: 'lia-2', name: 'Rafael Aquino', email: 'rafael.a@agila.ph', avatar: 'RA', department: 'Liaison' },
  { id: 'lia-3', name: 'Carlos Mendoza', email: 'carlos.m@agila.ph', avatar: 'CM', department: 'Liaison' },
];

export const CURRENT_LIAISON: AOTeamMember = LIAISON_TEAM[0];

// ── Liaison Tasks ─────────────────────────────────────────
// These are tasks assigned to the Liaison department by AOs or Compliance.
export const INITIAL_LIAISON_TASKS: AOTask[] = [
  {
    id: 'lia-task-1',
    title: 'BIR 2551Q Filing - Liaison Run',
    description: 'Submit the Q1 2551Q filing at BIR RDO 044 Makati. Bring 3 copies of the return, payment form, and photocopy of COR.',
    status: 'In Progress',
    priority: 'High',
    clientId: 'client-1',
    assigneeId: 'lia-1',
    dueDate: '2026-03-15',
    createdAt: '2026-03-08T09:00:00Z',
    updatedAt: '2026-03-11T08:00:00Z',
    comments: [
      { id: 'lc-1', authorId: 'lia-1', authorName: 'Bianca Torres', content: 'Queued at RDO 044. Estimated processing 2-3 hours.', createdAt: '2026-03-11T08:00:00Z' },
    ],
    tags: ['BIR', 'Filing', 'On-Site'],
  },
  {
    id: 'lia-task-2',
    title: "Mayor's Permit Renewal - Document Pickup",
    description: "Pick up updated barangay clearance and fire safety certificate from Taguig LGU. Schedule appointment first.",
    status: 'To Do',
    priority: 'Urgent',
    clientId: 'client-2',
    assigneeId: 'lia-2',
    dueDate: '2026-03-14',
    createdAt: '2026-03-03T10:00:00Z',
    updatedAt: '2026-03-03T10:00:00Z',
    comments: [],
    tags: ['LGU', 'Permit', 'Pickup'],
  },
  {
    id: 'lia-task-3',
    title: 'SEC GIS Submission',
    description: 'Submit the General Information Sheet at SEC Main Office, EDSA Greenfields. Bring notarized copy and audited FS.',
    status: 'Review',
    priority: 'High',
    clientId: 'client-2',
    assigneeId: 'lia-1',
    dueDate: '2026-03-18',
    createdAt: '2026-03-05T11:00:00Z',
    updatedAt: '2026-03-10T15:00:00Z',
    comments: [
      { id: 'lc-2', authorId: 'lia-1', authorName: 'Bianca Torres', content: 'AO reviewing the GIS package before I head to SEC.', createdAt: '2026-03-10T15:00:00Z' },
    ],
    tags: ['SEC', 'Submission', 'On-Site'],
  },
  {
    id: 'lia-task-4',
    title: 'DTI Certificate Collection',
    description: 'Collect the renewed DTI certificate from the DTI-NCR office. Reference No. DTI-2026-0428.',
    status: 'Done',
    priority: 'Medium',
    clientId: 'client-8',
    assigneeId: 'lia-2',
    dueDate: '2026-03-08',
    createdAt: '2026-02-28T09:00:00Z',
    updatedAt: '2026-03-07T16:00:00Z',
    comments: [
      { id: 'lc-3', authorId: 'lia-2', authorName: 'Rafael Aquino', content: 'Certificate collected. Scanned copy sent to AO.', createdAt: '2026-03-07T16:00:00Z' },
    ],
    tags: ['DTI', 'Pickup'],
  },
  {
    id: 'lia-task-5',
    title: 'SSS R-5 Form Submission',
    description: 'Submit SSS R-5 (Report of Separation) for resigned employees to SSS Makati Branch.',
    status: 'To Do',
    priority: 'Medium',
    clientId: 'client-3',
    assigneeId: 'lia-3',
    dueDate: '2026-03-20',
    createdAt: '2026-03-09T08:00:00Z',
    updatedAt: '2026-03-09T08:00:00Z',
    comments: [],
    tags: ['SSS', 'Submission'],
  },
  {
    id: 'lia-task-6',
    title: 'BIR 1601-C eFPS Submission',
    description: 'Submit BIR 1601-C via eFPS. AO has prepared the return — verify and submit once approved.',
    status: 'In Progress',
    priority: 'High',
    clientId: 'client-1',
    assigneeId: 'lia-1',
    dueDate: '2026-03-12',
    createdAt: '2026-03-10T09:00:00Z',
    updatedAt: '2026-03-11T09:00:00Z',
    comments: [
      { id: 'lc-4', authorId: 'lia-1', authorName: 'Bianca Torres', content: 'Waiting for AO final review. Will submit once confirmed.', createdAt: '2026-03-11T09:00:00Z' },
    ],
    tags: ['BIR', 'eFPS', 'Filing'],
  },
  {
    id: 'lia-task-7',
    title: 'PhilHealth PRF Submission',
    description: 'Submit PhilHealth Premium Remittance Form at the PhilHealth Regional Office, Pasig.',
    status: 'To Do',
    priority: 'Low',
    clientId: 'client-4',
    assigneeId: 'lia-3',
    dueDate: '2026-03-25',
    createdAt: '2026-03-10T10:00:00Z',
    updatedAt: '2026-03-10T10:00:00Z',
    comments: [],
    tags: ['PhilHealth', 'Submission'],
  },
  {
    id: 'lia-task-8',
    title: 'DOLE Compliance Visit',
    description: 'Accompany DOLE inspector during scheduled compliance visit. Prepare OSHS checklist and employment records.',
    status: 'To Do',
    priority: 'Urgent',
    clientId: 'client-9',
    assigneeId: 'lia-2',
    dueDate: '2026-03-22',
    createdAt: '2026-03-11T08:00:00Z',
    updatedAt: '2026-03-11T08:00:00Z',
    comments: [],
    tags: ['DOLE', 'Compliance', 'On-Site'],
  },
  {
    id: 'lia-task-9',
    title: 'Pag-IBIG HDMF Remittance Run',
    description: 'Process Pag-IBIG remittance at Pag-IBIG Fund office, Mandaluyong. Bring ML-1 and HDMF membership forms.',
    status: 'In Progress',
    priority: 'Medium',
    clientId: 'client-6',
    assigneeId: 'lia-3',
    dueDate: '2026-03-18',
    createdAt: '2026-03-05T10:00:00Z',
    updatedAt: '2026-03-10T14:00:00Z',
    comments: [
      { id: 'lc-5', authorId: 'lia-3', authorName: 'Carlos Mendoza', content: 'Membership forms ready. Heading to Pag-IBIG office tomorrow.', createdAt: '2026-03-10T14:00:00Z' },
    ],
    tags: ['Pag-IBIG', 'Remittance', 'On-Site'],
  },
  {
    id: 'lia-task-10',
    title: 'BIR Registration Update - RDO Transfer',
    description: 'Process RDO transfer for client relocating from Quezon City to Makati. Submit BIR Form 1905.',
    status: 'To Do',
    priority: 'High',
    clientId: 'client-3',
    assigneeId: 'lia-2',
    dueDate: '2026-03-28',
    createdAt: '2026-03-11T11:00:00Z',
    updatedAt: '2026-03-11T11:00:00Z',
    comments: [],
    tags: ['BIR', 'Registration', 'On-Site'],
  },
];

// ── Calendar Events ───────────────────────────────────────
export interface CalendarEvent {
  id: string;
  title: string;
  date: string;           // YYYY-MM-DD
  startTime: string;      // HH:mm
  endTime: string;        // HH:mm
  type: 'filing' | 'pickup' | 'on-site' | 'meeting' | 'deadline';
  location?: string;
  clientId?: string;
  clientName?: string;
  assigneeId: string;
  assigneeName: string;
  taskId?: string;
  notes?: string;
}

export const INITIAL_CALENDAR_EVENTS: CalendarEvent[] = [
  // Week of Mar 11 (current week)
  {
    id: 'evt-1',
    title: 'BIR 2551Q Filing',
    date: '2026-03-11',
    startTime: '09:00',
    endTime: '12:00',
    type: 'filing',
    location: 'BIR RDO 044, Makati',
    clientId: 'client-1',
    clientName: 'Villanueva Trading Co.',
    assigneeId: 'lia-1',
    assigneeName: 'Bianca Torres',
    taskId: 'lia-task-1',
    notes: 'Bring 3 copies of return + payment form',
  },
  {
    id: 'evt-2',
    title: 'BIR 1601-C eFPS Submission',
    date: '2026-03-12',
    startTime: '10:00',
    endTime: '11:00',
    type: 'filing',
    location: 'Online - eFPS Portal',
    clientId: 'client-1',
    clientName: 'Villanueva Trading Co.',
    assigneeId: 'lia-1',
    assigneeName: 'Bianca Torres',
    taskId: 'lia-task-6',
  },
  {
    id: 'evt-3',
    title: 'Team Sync Meeting',
    date: '2026-03-12',
    startTime: '14:00',
    endTime: '15:00',
    type: 'meeting',
    location: 'Agila Office, Makati',
    assigneeId: 'lia-1',
    assigneeName: 'Bianca Torres',
    notes: 'Weekly liaison team status sync',
  },
  {
    id: 'evt-4',
    title: 'Barangay Clearance Pickup',
    date: '2026-03-13',
    startTime: '08:30',
    endTime: '10:30',
    type: 'pickup',
    location: 'Taguig City Hall',
    clientId: 'client-2',
    clientName: 'Lim Holdings Inc.',
    assigneeId: 'lia-2',
    assigneeName: 'Rafael Aquino',
    taskId: 'lia-task-2',
  },
  {
    id: 'evt-5',
    title: 'Fire Safety Certificate Pickup',
    date: '2026-03-13',
    startTime: '13:00',
    endTime: '15:00',
    type: 'pickup',
    location: 'BFP Taguig Station',
    clientId: 'client-2',
    clientName: 'Lim Holdings Inc.',
    assigneeId: 'lia-2',
    assigneeName: 'Rafael Aquino',
    taskId: 'lia-task-2',
  },
  {
    id: 'evt-6',
    title: "Mayor's Permit Filing Deadline",
    date: '2026-03-14',
    startTime: '09:00',
    endTime: '09:00',
    type: 'deadline',
    clientId: 'client-2',
    clientName: 'Lim Holdings Inc.',
    assigneeId: 'lia-2',
    assigneeName: 'Rafael Aquino',
    taskId: 'lia-task-2',
  },
  // Week of Mar 16
  {
    id: 'evt-7',
    title: 'SEC GIS Submission',
    date: '2026-03-16',
    startTime: '09:00',
    endTime: '12:00',
    type: 'filing',
    location: 'SEC Main Office, EDSA Greenfields',
    clientId: 'client-2',
    clientName: 'Lim Holdings Inc.',
    assigneeId: 'lia-1',
    assigneeName: 'Bianca Torres',
    taskId: 'lia-task-3',
  },
  {
    id: 'evt-8',
    title: 'Pag-IBIG HDMF Remittance',
    date: '2026-03-17',
    startTime: '09:00',
    endTime: '11:30',
    type: 'filing',
    location: 'Pag-IBIG Fund, Mandaluyong',
    clientId: 'client-6',
    clientName: 'Santos & Co. CPAs',
    assigneeId: 'lia-3',
    assigneeName: 'Carlos Mendoza',
    taskId: 'lia-task-9',
  },
  {
    id: 'evt-9',
    title: 'SEC GIS Submission Deadline',
    date: '2026-03-18',
    startTime: '09:00',
    endTime: '09:00',
    type: 'deadline',
    clientId: 'client-2',
    clientName: 'Lim Holdings Inc.',
    assigneeId: 'lia-1',
    assigneeName: 'Bianca Torres',
    taskId: 'lia-task-3',
  },
  {
    id: 'evt-10',
    title: 'SSS R-5 Submission',
    date: '2026-03-19',
    startTime: '10:00',
    endTime: '12:00',
    type: 'filing',
    location: 'SSS Makati Branch',
    clientId: 'client-3',
    clientName: 'Garcia Construction Corp.',
    assigneeId: 'lia-3',
    assigneeName: 'Carlos Mendoza',
    taskId: 'lia-task-5',
  },
  {
    id: 'evt-11',
    title: 'Team Sync Meeting',
    date: '2026-03-19',
    startTime: '14:00',
    endTime: '15:00',
    type: 'meeting',
    location: 'Agila Office, Makati',
    assigneeId: 'lia-1',
    assigneeName: 'Bianca Torres',
  },
  // Week of Mar 22
  {
    id: 'evt-12',
    title: 'DOLE Compliance Visit',
    date: '2026-03-22',
    startTime: '09:00',
    endTime: '16:00',
    type: 'on-site',
    location: 'Client premises, Pasig',
    clientId: 'client-9',
    clientName: 'Agustin IT Solutions',
    assigneeId: 'lia-2',
    assigneeName: 'Rafael Aquino',
    taskId: 'lia-task-8',
    notes: 'Full-day visit. Bring OSHS checklist.',
  },
  {
    id: 'evt-13',
    title: 'PhilHealth PRF Submission',
    date: '2026-03-24',
    startTime: '09:30',
    endTime: '11:30',
    type: 'filing',
    location: 'PhilHealth Regional Office, Pasig',
    clientId: 'client-4',
    clientName: 'Reyes Digital Marketing',
    assigneeId: 'lia-3',
    assigneeName: 'Carlos Mendoza',
    taskId: 'lia-task-7',
  },
  {
    id: 'evt-14',
    title: 'BIR RDO Transfer Filing',
    date: '2026-03-26',
    startTime: '09:00',
    endTime: '12:00',
    type: 'filing',
    location: 'BIR RDO 039, Quezon City',
    clientId: 'client-3',
    clientName: 'Garcia Construction Corp.',
    assigneeId: 'lia-2',
    assigneeName: 'Rafael Aquino',
    taskId: 'lia-task-10',
    notes: 'Submit BIR Form 1905 at old RDO first',
  },
  {
    id: 'evt-15',
    title: 'Team Sync Meeting',
    date: '2026-03-26',
    startTime: '14:00',
    endTime: '15:00',
    type: 'meeting',
    location: 'Agila Office, Makati',
    assigneeId: 'lia-1',
    assigneeName: 'Bianca Torres',
  },
];
